Fix + log

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -235,6 +235,8 @@ jobs:
 
       - name: Apply ZRAM
         run: |
+          set -x
+
           cd "$CONFIG/kernel_platform"
 
           echo "Copy files"
@@ -246,33 +248,23 @@ jobs:
 
           echo "Apply LZ4KD"
 
-          cp ../../SukiSU_patch/other/zram/zram_patch/${{ github.event.inputs.android_version }}/lz4kd.patch ./common
+          cp ../../SukiSU_patch/other/zram/zram_patch/${{ inputs.kernel_version }}/lz4kd.patch ./common
+          cp ../../SukiSU_patch/other/zram/zram_patch/${{ inputs.kernel_version }}/lz4k_oplus.patch ./common
           pushd ./common
           patch -p1 -F 3 < lz4kd.patch
+          patch -p1 -F 3 < lz4k_oplus.patch
           popd
 
           echo "Adjust configuration"
 
           CONFIG_FILE=./common/arch/arm64/configs/gki_defconfig
-          echo "CONFIG_ZSMALLOC=y" >> "$CONFIG_FILE"
-          sed -i 's/CONFIG_ZRAM=m/CONFIG_ZRAM=y/g' "$CONFIG_FILE"
-          if [  -e ./common/modules.bzl ]; then
-            sed -i 's/"drivers\/block\/zram\/zram\.ko",//g; s/"mm\/zsmalloc\.ko",//g' "./common/modules.bzl"
-          fi
-
-          if [  -e ./msm-kernel/modules.bzl ]; then
-            sed -i 's/"drivers\/block\/zram\/zram\.ko",//g; s/"mm\/zsmalloc\.ko",//g' "./msm-kernel/modules.bzl"
-            echo "CONFIG_ZSMALLOC=y" >> "msm-kernel/arch/arm64/configs/${{ github.event.inputs.soc }}-GKI.config"
-            echo "CONFIG_ZRAM=y" >> "msm-kernel/arch/arm64/configs/${{ github.event.inputs.soc }}-GKI.config"
-          fi
-
-          echo "CONFIG_MODULE_SIG_FORCE=n" >> "$CONFIG_FILE"
 
           if grep -q "CONFIG_ZSMALLOC=y" "$CONFIG_FILE" && grep -q "CONFIG_ZRAM=y" "$CONFIG_FILE"; then
             echo "CONFIG_CRYPTO_LZ4HC=y" >> "$CONFIG_FILE"
             echo "CONFIG_CRYPTO_LZ4K=y" >> "$CONFIG_FILE"
             echo "CONFIG_CRYPTO_LZ4KD=y" >> "$CONFIG_FILE"
             echo "CONFIG_CRYPTO_842=y" >> "$CONFIG_FILE"
+            echo "CONFIG_CRYPTO_LZ4K_OPLUS=y" >> "$CONFIG_FILE"
             echo "CONFIG_ZRAM_WRITEBACK=y" >> "$CONFIG_FILE"
           fi
 
@@ -384,7 +376,7 @@ jobs:
 
           BUILD_TYPE="gki"
           BAZEL_ARGS=(--jobs=$(nproc --all) --lto=thin --verbose_failures)
-          # OnePlus 13 adjustments 
+          # OnePlus 13 adjustments
           BUILD_TYPE="perf"
           BAZEL_ARGS+=(-g)
 
@@ -409,6 +401,54 @@ jobs:
           else
             LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} "$BUILD_TYPE"
           fi
+
+      - name: Download and Unzip ZRAM
+        id: zram_find
+        run: |
+          set -e
+          sudo apt install -y unzip
+          curl -s https://api.github.com/repos/FurLC/ZRAM-Module/releases/latest | \
+            grep "browser_download_url" | grep "ZRAM-Module-.*\.zip" | cut -d '"' -f 4 | xargs wget -N
+          unzip "$(ls -t ZRAM-Module-*.zip | head -1)" -d ZRAM-Module
+          target="./ZRAM-Module/zram/zram.ko"
+          search_paths=(
+            "./$CONFIG/kernel_platform/out"
+            "./$CONFIG/device/qcom"
+          )
+          zram_path=""
+          for path in "${search_paths[@]}"; do
+            zram_path=$(find "$path" -type f -name "zram.ko" | head -n 1)
+            [ -n "$zram_path" ] && break
+          done
+          if [ -z "$zram_path" ]; then
+            zram_path=$(find "./$CONFIG" -type f -name "zram.ko" | head -n 1)
+          fi
+          if [ -n "$zram_path" ] && [ -f "$zram_path" ]; then
+            echo " ZRAM module file finally located at: $zram_path "
+            mkdir -p "$(dirname "$target")"
+            if [ "$(realpath "$zram_path")" != "$(realpath "$target")" ]; then
+              cp "$zram_path" "$target"
+            else
+              echo "Skip copy"
+            fi
+
+            pushd ./ZRAM-Module
+            echo "ZRAM_ALGO=lz4kd" > ./config.prop
+            echo "ZRAM_SIZE=12884901888" >> ./config.prop
+            zip -r -d zram-module.zip ./*
+            popd
+          else
+            echo "Not found"
+            echo "upload=false" >> "$GITHUB_OUTPUT"
+            exit 0
+          fi
+
+      - name: Upload ZRAM Module
+        if: ${{ steps.zram_find.outputs.upload != 'false' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: zram-module-${{ env.CONFIG }}
+          path: zram-module.zip
 
       - name: Copy and patch images
         run: |
